services:
  tm1:
    container_name: tm1-rocky9
    image: kseed-docker1.knowledgeseed.local:3000/tm1-docker:2.1.4-rocky9
    # The purpose of this is to make sure the container doesn't write back to the host bind mount,
    entrypoint: >
      bash -c "cp -r /tm1models /docker-entrypoint-initdb.d/ && /docker-entrypoint.sh"
    volumes:
      - ./tm1models:/tm1models
      - ./cogstartup.xml:/docker-entrypoint-initdb.d/cogstartup.xml
    healthcheck:
      test: "curl -f http://localhost:5360/api/v1/"
      interval: 5s
      timeout: 2m
      retries: 10
    ports:
      - 5898:5898
      - 5360:5360

  arc:
    container_name: arc
    image: kseed-docker1.knowledgeseed.local:3000/arc-docker:5.2.0-linux64-v1
    ports:
      - 7070:7070
    volumes:
      - ./settings.yml:/settings.yml
      - ./License:/License

      